version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"                    # host:container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue
      - green

  blue:
    image: bluegreen-node:latest
    environment:
      - COLOR=blue
    ports:
      - "3000:3000"

  green:
    image: bluegreen-node:latest
    environment:
      - COLOR=green
    ports:
      - "3001:3000"
